[project]
name = "taipy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "taipy",
]

[tool.uv.sources]
taipy = { workspace = true }

[scenarios]
scenario = "Horror"
